### ISSUE TITLE
ERROR: 'py-vgdl[all]' is not a valid editable requirement.

### ISSUE THREAD

**Issue by matanmazor** [rubenvereecken/py-vgdl#5]
I tried to install py-vgdl on a windows machine by cloning the repository and then typing "pip install -e 'py-vgdl[all]' ". I'm getting the following error message:

> ERROR: 'py-vgdl[all]' is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with svn+, git+, hg+, or bzr+).

what am I doing wrong?

[also, I couldn't get py-vgdl to work on my anaconda installation for reason described in issue #2 ]

**Comment by rubenvereecken** [comment]
`pip install -e` would be used for an 'editable' repository, meaning you have the library on disk somewhere and you simply link to it, instead of a regular pip installation. That's what I use for developing for example. So that requires for `py-vgdl` to be a valid path to the repository. I have a feeling it isn't in your case, ie `./py-vgdl` does not exist. You might be in the wrong directory? 

If that's _not_ the case then I've got no idea and you should consider an installation of py-vgdl as a library, then you'll need to download the example .txt files elsewhere. I can point out how to do it when we know more.

**Comment by matanmazor** [comment]
Thanks @rubenvereecken ! 
I'm actually running the command from the mother directory of py-vgdl, so I assumed it should work:

>\> if EXIST .\py-vgdl (echo Yes)
Yes
\> pip install -e 'py-vgdl[all]'
ERROR: 'py-vgdl[all]' is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with svn+, git+, hg+, or bzr+).

I'm getting a different error message using this method:
>\> pip install 'git+https://github.com/rubenvereecken/py-vgdl/#egg=vgdl[all]'
ERROR: Could not find a version that satisfies the requirement py-vgdl (from versions: none)
ERROR: No matching distribution found for py-vgdl

By "installation of py-vgdl as a library" do you mean pip install? Because I couldn't get this to work either :-)

I'm getting similar error messages when trying to run these commands inside an anaconda prompt that runs on my windows machine (no WSL), and directly in the windows cmd.

**Comment by rubenvereecken** [comment]
You're right, that should have worked. Let's pursue the second approach
then. That should also have worked.. but maybe we can simplify it:

`pip install 'git+https://github.com/rubenvereecken/py-vgdl'`

Does that work maybe? It's tricky as I don't have a Windows system to test
this on.

**Comment by matanmazor** [comment]
We're getting closer! It now "successfuly built vgdl pybrain", "successfully installed pybrain", but then:

> Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\pip-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\_internal\__init__.py", line 78, in main
    return command.main(cmd_args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\_internal\cli\base_command.py", line 228, in main
    timeout=min(5, options.timeout)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\_internal\cli\base_command.py", line 93, in _build_session
    insecure_hosts=options.trusted_hosts,
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\_internal\download.py", line 344, in __init__
    self.headers["User-Agent"] = user_agent()
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\_internal\download.py", line 134, in user_agent
    setuptools_version = get_installed_version("setuptools")
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\_internal\utils\misc.py", line 902, in get_installed_version
    working_set = pkg_resources.WorkingSet()
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 565, in __init__
    self.add_entry(entry)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 621, in add_entry
    for dist in find_distributions(entry, True):
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1886, in find_eggs_in_zip
    if metadata.has_metadata('PKG-INFO'):
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1405, in has_metadata
    return self.egg_info and self._has(self._fn(self.egg_info, name))
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1760, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1637, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1594, in load
    mtime = os.stat(path).st_mtime
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\vgdl-1.0-py3.7.egg'

**Comment by matanmazor** [comment]
But it did work outside anaconda!
With a small difference - no apostrophe: (pip install git+https://github.com/rubenvereecken/py-vgdl)

AND NOW THERE ARE ALIENS ON MY SCREEN NOW HOW AWESOME IS THAT

Thanks Ruben!

**Comment by rubenvereecken** [comment]
:tada:
