### ISSUE TITLE
pygame.error: No available video device

### ISSUE THREAD

**Issue by rubenvereecken** [rubenvereecken/py-vgdl#6]
Thanks! 
The error that I'm getting now is 

> python -m vgdl.util.humanplay.play_vgdl vgdl/games/aliens_lvl0.txt
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
WARNING:vgdl.util.humanplay.human trace_path provided but could not find the gym_recording package
Traceback (most recent call last):
  File "/home/matanm/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/matanm/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mnt/c/Users/mmazor/Documents/software/py-vgdl/vgdl/util/humanplay/play_vgdl.py", line 101, in <module>
    main()
  File "/mnt/c/Users/mmazor/Documents/software/py-vgdl/vgdl/util/humanplay/play_vgdl.py", line 89, in main
    controller = controller_cls(env_name, args.tracedir)
  File "/mnt/c/Users/mmazor/Documents/software/py-vgdl/vgdl/util/humanplay/human.py", line 122, in __init__
    self.env.render(mode='human')
  File "/mnt/c/Users/mmazor/Documents/software/py-vgdl/vgdl/interfaces/gym/env.py", line 130, in render
    self.renderer.init_screen(headless)
  File "/mnt/c/Users/mmazor/Documents/software/py-vgdl/vgdl/render/pygame.py", line 42, in init_screen
    self.display = pygame.display.set_mode(self.display_dims, pygame.RESIZABLE, 32)
pygame.error: No available video device

But I suspect this must have more to do with the fact that I'm running anaconda from a Windows Subsystem for Linux?

_Originally posted by @matanmazor in https://github.com/rubenvereecken/py-vgdl/issues/2#issuecomment-547440947_

**Comment by rubenvereecken** [comment]
It doesn't look possible to run pygame in that way. You might be able to get away without using a video driver, so without any visuals: https://stackoverflow.com/questions/15933493/pygame-error-no-available-video-device

But I'm not sure whether SDL can work on WSL: https://stackoverflow.com/questions/45297979/python-running-pygame-through-bash-on-ubuntu-on-windows

**Comment by matanmazor** [comment]
Thanks! In that case I guess I'm stuck with issue #5.

**Comment by EndingCredits** [comment]
I usually use
```
    try:
        os.environ["DISPLAY"]
    except:
        os.environ["SDL_VIDEODRIVER"] = "dummy"
```

**Comment by rubenvereecken** [comment]
@matanmazor Does the suggestion by @EndingCredits work?
